version: "3"

services:
  app:
    build:
      context: ./packages/app
      dockerfile: ./Dockerfile
      #
      # this app is built statically so we cannot inject env vars at runtime
      # we use args to expose them as env var *during the build phase, inside the container*
      #
      args:
        API_URL: "/api"
    depends_on:
      - api
    ports:
      - 3000:80

  api:
    ports:
      - 1337:1337
    build:
      context: ./packages/api
      dockerfile: ./Dockerfile


