version: "3"

services:
  tremplin-app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    image: ${REGISTRY_IMAGE}/app:${APP_VERSION}
    depends_on:
      - tremplin-api
    ports:
      - 3000:3000

  tremplin-api:
    ports:
      - 1337:1337
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    image: ${REGISTRY_IMAGE}/api:${APP_VERSION}

