version: "3"

services:
  tremplin-app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    depends_on:
      - tremplin-api
    ports:
      - 3000:80

  tremplin-api:
    ports:
      - 1337:1337
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile

