---
kind: Service
apiVersion: v1
metadata:
  name: tremplin-frontend${BRANCH_NAME}
  labels:
    app: tremplin-frontend${BRANCH_NAME}
    branch: tremplin${BRANCH_NAME}
spec:
  selector:
    app: tremplin-frontend${BRANCH_NAME}
  ports:
  - port: ${PORT}
    name: frontend
