version: "3"

services:
  tremplin_api:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/tremplin/api:latest
    ports:
      - "9090:9090"
    environment:
      TZ: Europe/Paris
      PORT: 9090

  tremplin_app:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/tremplin/app:latest
    ports:
      - "3000:3000"
    environment:
      TZ: Europe/Paris
      API_URL: http://46.101.207.198:9090/api
